name: Parse and Combine Pull Request

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - main

concurrency:
  group: 'appfilter'
  cancel-in-progress: true

jobs:
  parse_and_combine:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
      - run: pip install -r .github/workflows/requirements.txt
      
      - name: Execute Python Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/workflows/combine_appfilter.py
